language: python
python: "3.6"
install: pip install -r requirements-dev.txt
env:
  - GEAR_DATABASE_USER='travis' GEAR_DATABASE_PASSWORD=''
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - npm install
  - npm install -g uglify-js yuglify
  - python manage.py collectstatic --verbosity=0
  - psql postgres -c 'create role ws login'
  - psql postgres -c 'alter user ws createdb'
script: 
  - black --check ws
  - isort -rc --check ws
  - python manage.py test
