language: python
python: "3.6"
before_install: pip install poetry
install:
  - make install
env:
  - GEAR_DATABASE_USER='travis' GEAR_DATABASE_PASSWORD=''
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - npm install
  - npm install -g uglify-js yuglify
  - WS_DJANGO_TEST=1 python manage.py collectstatic --verbosity=0
  - psql postgres -c 'create role ws login'
  - psql postgres -c 'alter user ws createdb'
script: 
  - make check
after_success:
  - coveralls
