[tool.black]
include = '\.py$'
# Don't attempt to normalize strings
# (Preserves the convention of "single quotes for data, double quotes for humans")
skip-string-normalization = true

[tool.isort]
line_length = 88
known_first_party = "ws"
multi_line_output = 3
include_trailing_comma = true

[tool.poetry]
name = "ws"
version = "0.1.0"
description = "The MIT Outing Club's trip management system"
license = "GPL-3.0"
readme = "README.md"
homepage = "https://mitoc-trips.mit.edu"
repository = "https://github.com/DavidCain/mitoc-trips/"
authors = ["David Cain <davidjosephcain@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
Django = "^1.11.23"
PyJWT = "*"
celery = "^4.2"
django-allauth = "^0.38.0"
django-angular = "^2.1"
django-cors-headers = "*"
django-localflavor = "*"
django-phonenumber-field = "<2.4.0"  # Version 2.4.0 affects `cell_phone` fixture
django-pipeline = "*"
django-smtp-ssl = "*"
gspread = "^3.0.1"
markdown2 = "*"
mitoc-const = "^0.4.0"
mysqlclient = "^1.3.14"
oauth2client = "*"
phonenumberslite = "*"
psycopg2-binary = "*"
pytz = "*"
raven = "*"
requests = "*"

# Optional dependencies for local development
# (Included here, since extras cannot refer to dev dependencies)
django-debug-toolbar = { version = "*", optional = true }
ipdb = { version = "*", optional = true }

[tool.poetry.extras]
debugging = ["django-debug-toolbar", "ipdb"]

[tool.poetry.dev-dependencies]
beautifulsoup4 = "*"
black = { version = "*", allows-prereleases = true }
factory_boy = "^2.9.0"
freezegun = "^0.3.9"
isort = "*"
lxml = "*"
pylint = "*"
